version: '3'
services:

  nginx:  
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro

  site1:
    build: app/.

  site2:
    image: containous/whoami

  site3:
    image: containous/whoami

  gateway:
    image: jwilder/whoami
    environment:
      VIRTUAL_HOST: test.localhost