version : "3"
services:
  
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes: 
      - ./elasticsearch-conf/default.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:7.6.2
    ports:
      - "9600:9600"
      - "5000:5000"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes: 
      - ./logstash-conf:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.6.2
    ports:
      - "8200:8200"
    volumes: 
      - ./apm-conf/default.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.6.2
    ports:
      - "5601:5601"
    volumes: 
      - ./kibana-conf:/usr/share/kibana/config/
    depends_on:
      - elasticsearch

  api:
    build: ./api
    ports: 
      - "8080:8080"
    depends_on:
      - apm-server